name: imis
description: "Integrated Management Information System"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  build_runner: ^2.4.15
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  motion_toast: ^2.12.1
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  percent_indicator: ^4.2.4
  table_calendar: ^3.2.0
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  uuid: ^4.0.0
  jwt_decode_full: ^0.9.2
  jwt_decoder: ^2.0.1
  path_provider: ^2.0.11
  open_file: ^3.2.1
  universal_html: ^2.2.3
  http: ^1.1.0
  fl_chart: ^0.63.0
  number_inc_dec: ^0.8.0
  font_awesome_flutter: ^10.8.0
  dropdown_search: ^5.0.6
  collection: ^1.18.0
  dotted_border: ^2.0.0
  async: ^2.11.0
  syncfusion_flutter_pdfviewer: ^30.1.37
  webview_flutter_wkwebview: ^3.11.0
  webview_windows: ^0.4.0
  responsive_sizer: ^3.3.1
  webview_flutter: ^4.13.0
  
 


 

 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/CRMC.png 
    - assets/logo.png
    - assets/lock.png
    - assets/profile.png
    - assets/iconprofile.png
    - assets/users.png
    - assets/team.png
    - assets/office.png
    - assets/auditor.png
    - assets/pic1.jpg
    - assets/pic2.jpg
    - assets/forgotpass.png
   
